Update scripts

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -20,8 +20,70 @@ env:
   CODECOV_UNIQUE_NAME: CODECOV_UNIQUE_NAME-${{ github.run_id }}-${{ github.run_number }}
 
 jobs:
+  # Code-Quality-Checks:
+  #   name: Performs linting, formatting, type-checking, checking for different source and target branch
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout the Repository
+  #       uses: actions/checkout@v4
+
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '22.x'
+
+  #     - name: Install Dependencies
+  #       run: npm install
+
+  #     - name: Count number of lines
+  #       run: |
+  #         chmod +x ./.github/workflows/countline.py
+  #         ./.github/workflows/countline.py --lines 600 --exclude_files src/screens/LoginPage/LoginPage.tsx src/GraphQl/Queries/Queries.ts src/screens/OrgList/OrgList.tsx src/GraphQl/Mutations/mutations.ts src/components/EventListCard/EventListCardModals.tsx src/components/TagActions/TagActionsMocks.ts src/utils/interfaces.ts src/screens/MemberDetail/MemberDetail.tsx
+
+  #     - name: Get changed TypeScript files
+  #       id: changed-files
+  #       uses: tj-actions/changed-files@v45
+  #     - name: Check formatting
+  #       if: steps.changed-files.outputs.only_changed != 'true'
+  #       run: npm run format:check
+        
+  #     - name: Run formatting if check fails
+  #       if: failure()
+  #       run: npm run format:fix
+
+  #     - name: Check for type errors
+  #       if: steps.changed-files.outputs.only_changed != 'true'
+  #       run: npm run typecheck
+
+  #     - name: Check for linting errors in modified files
+  #       if: steps.changed-files.outputs.only_changed != 'true'
+  #       env: 
+  #         CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+  #       run: npx eslint ${CHANGED_FILES}
+        
+  #     - name: Check for TSDoc comments
+  #       run: npm run check-tsdoc # Run the TSDoc check script
+
+  #     - name: Check for localStorage Usage
+  #       run: |
+  #         chmod +x scripts/githooks/check-localstorage-usage.js
+  #         node scripts/githooks/check-localstorage-usage.js --scan-entire-repo
+
+  #     - name: Compare translation files
+  #       run: |
+  #         chmod +x .github/workflows/compare_translations.py
+  #         python .github/workflows/compare_translations.py --directory public/locales
+
+  #     - name: Check if the source and target branches are different
+  #       if: ${{ github.event.pull_request.base.ref == github.event.pull_request.head.ref }}
+  #       run: |
+  #         echo "Source Branch ${{ github.event.pull_request.head.ref }}"
+  #         echo "Target Branch ${{ github.event.pull_request.base.ref }}"
+  #         echo "Error: Source and Target Branches are the same. Please ensure they are different."
+  #         exit 1
+
+
   Code-Quality-Checks:
-    name: Performs linting, formatting, type-checking, checking for different source and target branch
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the Repository
@@ -32,55 +94,11 @@ jobs:
         with:
           node-version: '22.x'
 
-      - name: Install Dependencies
-        run: npm install
-
-      - name: Count number of lines
+      - name: Run Code Quality Checks
         run: |
-          chmod +x ./.github/workflows/countline.py
-          ./.github/workflows/countline.py --lines 600 --exclude_files src/screens/LoginPage/LoginPage.tsx src/GraphQl/Queries/Queries.ts src/screens/OrgList/OrgList.tsx src/GraphQl/Mutations/mutations.ts src/components/EventListCard/EventListCardModals.tsx src/components/TagActions/TagActionsMocks.ts src/utils/interfaces.ts src/screens/MemberDetail/MemberDetail.tsx
+          chmod +x .github/workflows/code_quality_checks.sh
+          ./.github/workflows/code_quality_checks.sh
 
-      - name: Get changed TypeScript files
-        id: changed-files
-        uses: tj-actions/changed-files@v45
-      - name: Check formatting
-        if: steps.changed-files.outputs.only_changed != 'true'
-        run: npm run format:check
-        
-      - name: Run formatting if check fails
-        if: failure()
-        run: npm run format:fix
-
-      - name: Check for type errors
-        if: steps.changed-files.outputs.only_changed != 'true'
-        run: npm run typecheck
-
-      - name: Check for linting errors in modified files
-        if: steps.changed-files.outputs.only_changed != 'true'
-        env: 
-          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
-        run: npx eslint ${CHANGED_FILES}
-        
-      - name: Check for TSDoc comments
-        run: npm run check-tsdoc # Run the TSDoc check script
-
-      - name: Check for localStorage Usage
-        run: |
-          chmod +x scripts/githooks/check-localstorage-usage.js
-          node scripts/githooks/check-localstorage-usage.js --scan-entire-repo
-
-      - name: Compare translation files
-        run: |
-          chmod +x .github/workflows/compare_translations.py
-          python .github/workflows/compare_translations.py --directory public/locales
-
-      - name: Check if the source and target branches are different
-        if: ${{ github.event.pull_request.base.ref == github.event.pull_request.head.ref }}
-        run: |
-          echo "Source Branch ${{ github.event.pull_request.head.ref }}"
-          echo "Target Branch ${{ github.event.pull_request.base.ref }}"
-          echo "Error: Source and Target Branches are the same. Please ensure they are different."
-          exit 1
 
   # Check-Sensitive-Files:
   #   if: ${{ github.actor != 'dependabot[bot]' && !contains(github.event.pull_request.labels.*.name, 'ignore-sensitive-files-pr') }}
@@ -152,58 +170,12 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      
-      - name: Get Changed Files
-        id: changed-files
+
+      - name: Run Sensitive Files Check
         uses: tj-actions/changed-files@v45
-
-      - name: Check Sensitive Files
         run: |
-          chmod +x .github/scripts/check_sensitive_files.sh
-          .github/scripts/check_sensitive_files.sh \
-            --files "$(cat <<EOF
-              .env*
-              .github/**
-              env.example
-              .node-version
-              .husky/**
-              scripts/**
-              src/style/** 
-              schema.graphql
-              package.json
-              package-lock.json
-              tsconfig.json
-              .gitignore
-              .eslintrc.json
-              .eslintignore
-              .prettierrc
-              .prettierignore
-              .nojekyll
-              vite.config.ts
-              docker-compose.yaml
-              Dockerfile
-              CODEOWNERS
-              LICENSE
-              setup.ts
-              .coderabbit.yaml
-              CODE_OF_CONDUCT.md
-              CODE_STYLE.md
-              CONTRIBUTING.md
-              DOCUMENTATION.md
-              INSTALLATION.md
-              ISSUE_GUIDELINES.md
-              PR_GUIDELINES.md
-              README.md
-              *.pem
-              *.key
-              *.cert
-              *.password
-              *.secret
-              *.credentials
-            EOF
-            )" \
-            --changed-files "${{ steps.changed-files.outputs.all_changed_files }}"
-
+          chmod +x .github/workflows/check_sensitive_files.sh
+          ./.github/workflows/check_sensitive_files.sh
 
   # Count-Changed-Files:
   #   if: ${{ github.actor != 'dependabot[bot]' }}
@@ -252,26 +224,6 @@ jobs:
           .github/scripts/count_changed_files.sh --count "${{ steps.changed-files.outputs.all_changed_files_count }}"
 
 
-  # Check-ESlint-Disable:
-  #   name: Check for eslint-disable
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
-
-  #     - name: Get changed files
-  #       id: changed-files
-  #       uses: tj-actions/changed-files@v45
-
-  #     - name: Set up Python
-  #       uses: actions/setup-python@v5
-  #       with:
-  #         python-version: 3.9
-
-  #     - name: Run Python script
-  #       run: |
-  #         python .github/workflows/eslint_disable_check.py --files ${{ steps.changed-files.outputs.all_changed_files }}
-
   Check-ESlint-Disable:
     name: Check for eslint-disable
     runs-on: ubuntu-latest
@@ -279,54 +231,39 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Get Changed Files
+      - name: Get changed files
         id: changed-files
         uses: tj-actions/changed-files@v45
 
-      - name: Run ESlint Disable Check
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.9
+
+      - name: Run Python script
         run: |
-          chmod +x .github/scripts/check_eslint_disable.sh
-          .github/scripts/check_eslint_disable.sh --files "${{ steps.changed-files.outputs.all_changed_files }}"
-
-
-
-  # Check-Code-Coverage-Disable:
-  #   name: Check for code coverage disable
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
-
-  #     - name: Get changed files
-  #       id: changed-files
-  #       uses: tj-actions/changed-files@v45
-
-  #     - name: Set up Python
-  #       uses: actions/setup-python@v5
-  #       with:
-  #         python-version: 3.9
-
-  #     - name: Run Python script
-  #       run: |
-  #         python .github/workflows/code_coverage_disable_check.py --files ${{ steps.changed-files.outputs.all_changed_files }} 
+          python .github/workflows/eslint_disable_check.py --files ${{ steps.changed-files.outputs.all_changed_files }}
 
 
   Check-Code-Coverage-Disable:
-    name: Check for Code Coverage Disable
+    name: Check for code coverage disable
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Get Changed Files
+      - name: Get changed files
         id: changed-files
         uses: tj-actions/changed-files@v45
 
-      - name: Run Code Coverage Disable Check
-        run: |
-          chmod +x .github/scripts/check_code_coverage_disable.sh
-          .github/scripts/check_code_coverage_disable.sh --files "${{ steps.changed-files.outputs.all_changed_files }}"
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.9
 
+      - name: Run Python script
+        run: |
+          python .github/workflows/code_coverage_disable_check.py --files ${{ steps.changed-files.outputs.all_changed_files }} 
 
 
   # Test-Application:
@@ -549,7 +486,6 @@ jobs:
           .github/scripts/start_app_without_docker.sh
 
 
-
   # Docker-Start-Check:
   #   name: Check if Talawa Admin app starts in Docker
   #   runs-on: ubuntu-latest
@@ -660,17 +596,6 @@ jobs:
           chmod +x .github/scripts/test_docusaurus.sh
           .github/scripts/test_docusaurus.sh
 
-
-  # Check-Target-Branch:
-  #   if: ${{ github.actor != 'dependabot[bot]' }}
-  #   name: Check Target Branch
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Check if the target branch is develop
-  #       if: github.event.pull_request.base.ref != 'develop-postgres'
-  #       run: |
-  #         echo "Error: Pull request target branch must be 'develop-postgres'. Please refer PR_GUIDELINES.md"
-  #         exit 1
   Check-Target-Branch:
     if: ${{ github.actor != 'dependabot[bot]' }}
     name: Check Target Branch
